/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario.de.alumnos;

import javax.swing.JOptionPane;

/**
 *
 * @author Josee
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TextName = new javax.swing.JTextField();
        TextNumero = new javax.swing.JTextField();
        TextCalle = new javax.swing.JTextField();
        TextColonia = new javax.swing.JTextField();
        TextNControl = new javax.swing.JTextField();
        TextFNacimiento = new javax.swing.JTextField();
        TextAMat = new javax.swing.JTextField();
        TextAPatern = new javax.swing.JTextField();
        CBXEstado = new javax.swing.JComboBox<>();
        CBXSexo = new javax.swing.JComboBox<>();
        CheckIngles = new javax.swing.JCheckBox();
        CheckEspañol = new javax.swing.JCheckBox();
        CheckFrances = new javax.swing.JCheckBox();
        CheckEstudia = new javax.swing.JCheckBox();
        CheckTrabaja = new javax.swing.JCheckBox();
        CheckAmbos = new javax.swing.JCheckBox();
        Button = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        OpcionesMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuTurno = new javax.swing.JMenu();
        TurnoVespertino = new javax.swing.JRadioButtonMenuItem();
        TurnoMatutino = new javax.swing.JRadioButtonMenuItem();
        MenuCarrera = new javax.swing.JMenu();
        RB_Programacion = new javax.swing.JRadioButtonMenuItem();
        RB_Electricidad = new javax.swing.JRadioButtonMenuItem();
        RB_RH = new javax.swing.JRadioButtonMenuItem();
        RB_MecInd = new javax.swing.JRadioButtonMenuItem();
        RB_Mecatronica = new javax.swing.JRadioButtonMenuItem();
        RB_Ofimatica = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario de alumnos");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        setLocation(new java.awt.Point(500, 0));
        setResizable(false);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido paterno:");

        jLabel3.setText("Fecha de nacimiento:");

        jLabel4.setText("Apellido materno:");

        jLabel5.setText("Numero de control:");

        jLabel6.setText("Estado:");

        jLabel7.setText("Colonia:");

        jLabel8.setText("Número:");

        jLabel10.setText("Sexo:");

        jLabel11.setText("Calle:");

        jLabel12.setText("Ocupación:");

        jLabel13.setText("Idioma nativo:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Datos personales:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Datos escolares:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Datos de domicilio:");

        TextName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNameActionPerformed(evt);
            }
        });

        TextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNumeroActionPerformed(evt);
            }
        });

        TextCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCalleActionPerformed(evt);
            }
        });

        TextColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextColoniaActionPerformed(evt);
            }
        });

        TextNControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNControlActionPerformed(evt);
            }
        });

        TextFNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFNacimientoActionPerformed(evt);
            }
        });

        TextAMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAMatActionPerformed(evt);
            }
        });

        TextAPatern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAPaternActionPerformed(evt);
            }
        });

        CBXEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hidalgo", "Veracruz", "Puebla", "Ciudad de Mexico", "Queretaro" }));
        CBXEstado.setSelectedIndex(-1);

        CBXSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        CBXSexo.setSelectedIndex(-1);

        CheckIngles.setText("Ingles");
        CheckIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInglesActionPerformed(evt);
            }
        });

        CheckEspañol.setText("Español");
        CheckEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckEspañolActionPerformed(evt);
            }
        });

        CheckFrances.setText("Frances");
        CheckFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckFrancesActionPerformed(evt);
            }
        });

        CheckEstudia.setText("Estudia");
        CheckEstudia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckEstudiaActionPerformed(evt);
            }
        });

        CheckTrabaja.setText("Trabaja");
        CheckTrabaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckTrabajaActionPerformed(evt);
            }
        });

        CheckAmbos.setText("Ambos");
        CheckAmbos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAmbosActionPerformed(evt);
            }
        });

        Button.setText("Enviar datos");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        OpcionesMenu.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem1.setText("Limpiar todo");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        OpcionesMenu.add(jMenuItem1);

        MenuTurno.setText("Turno");

        TurnoVespertino.setText("Vespertino");
        MenuTurno.add(TurnoVespertino);

        TurnoMatutino.setText("Matutino");
        MenuTurno.add(TurnoMatutino);

        OpcionesMenu.add(MenuTurno);

        MenuCarrera.setText("Carrera");

        RB_Programacion.setText("Programacion");
        RB_Programacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_ProgramacionActionPerformed(evt);
            }
        });
        MenuCarrera.add(RB_Programacion);

        RB_Electricidad.setText("Electricidad");
        MenuCarrera.add(RB_Electricidad);

        RB_RH.setText("Recursos Humanos");
        MenuCarrera.add(RB_RH);

        RB_MecInd.setText("Mecanica Industrial");
        MenuCarrera.add(RB_MecInd);

        RB_Mecatronica.setText("Mecatronica");
        MenuCarrera.add(RB_Mecatronica);

        RB_Ofimatica.setText("Ofimatica");
        RB_Ofimatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_OfimaticaActionPerformed(evt);
            }
        });
        MenuCarrera.add(RB_Ofimatica);

        OpcionesMenu.add(MenuCarrera);

        MenuBar.add(OpcionesMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel18)
                                .addComponent(jLabel14)))
                        .addComponent(jLabel19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBXSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 229, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CBXEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextCalle, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextColonia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextNControl, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFNacimiento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextAMat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextAPatern, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(CheckIngles)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckEspañol)))
                                .addGap(18, 18, 18)
                                .addComponent(CheckFrances))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckEstudia)
                                .addGap(18, 18, 18)
                                .addComponent(CheckTrabaja)
                                .addGap(18, 18, 18)
                                .addComponent(CheckAmbos))
                            .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(Button)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextAPatern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextAMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CBXSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CheckIngles)
                    .addComponent(CheckFrances)
                    .addComponent(CheckEspañol))
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextNControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(TextColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TextCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBXEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CheckEstudia)
                        .addComponent(CheckAmbos)
                        .addComponent(CheckTrabaja)))
                .addGap(43, 43, 43)
                .addComponent(Button)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNameActionPerformed
       
    }//GEN-LAST:event_TextNameActionPerformed

    private void TextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumeroActionPerformed

    private void TextCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCalleActionPerformed

    private void TextColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextColoniaActionPerformed

    private void TextNControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNControlActionPerformed

    private void TextAMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAMatActionPerformed

    private void TextAPaternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAPaternActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAPaternActionPerformed

    private void TextFNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFNacimientoActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        
         
        if (validarCampos()) 
        {
            JOptionPane.showMessageDialog(Formulario.this, "Haz llenado los datos", "OK", HEIGHT);
                    
           enviarDatos();
            
        
        } 
            else 
            {
                JOptionPane.showMessageDialog(Formulario.this, "Todos los campos deben ser completados", "Error", JOptionPane.ERROR_MESSAGE);
            }
    
        
    }//GEN-LAST:event_ButtonActionPerformed
 private void enviarDatos() {
     
            String Nombre = TextName.getText();
            String AM   = TextAMat.getText();
            String AP  = TextAPatern.getText();
            String Call  = TextCalle.getText();
            String Col   = TextColonia.getText();
            String FechaN  = TextFNacimiento.getText();
            String NControl   = TextNControl.getText();
            String Num  = TextNumero.getText();
            String Sex = (String )CBXSexo.getSelectedItem();   
            String Edo = (String) CBXEstado.getSelectedItem();
            
            String Idioma= null;
         
            if(CheckIngles.isSelected())
            {
                 Idioma = (String) CheckIngles.getText();
            }
            else if(CheckEspañol.isSelected())
            {
            
                Idioma = (String) CheckIngles.getText();
            }
            else if(CheckFrances.isSelected())
            {
            
                Idioma = (String) CheckFrances.getText();
            }
            
             Datos frame2 = new Datos();
             frame2.recibeNombre(Nombre);
             frame2.recibeAP(AP);
             frame2.recibeAM(AM);
             frame2.recibeIdioma(Idioma);
             frame2.recibeCall(Call);
             frame2.recibeCol(Col);
             frame2.recibeNum(Num);
             frame2.recibeEdo(Edo);
             frame2.recibeSexo(Sex);
             frame2.recibeNControl(NControl);
             frame2.recibeFechaNac(FechaN);
             
             frame2.setVisible(true);
 }
            
     private boolean validarCampos() {
        return  !TextName.getText().isEmpty() &&
                !TextAMat.getText().isEmpty() &&
                !TextAPatern.getText().isEmpty() &&
                !TextCalle.getText().isEmpty() &&
                !TextColonia.getText().isEmpty() &&
                !TextFNacimiento.getText().isEmpty() &&
                !TextNControl.getText().isEmpty() &&
                !TextNumero.getText().isEmpty();
    }
    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TextName.setText(" ");
        TextAMat.setText(" ");
        TextAPatern.setText(" ");
        TextCalle.setText(" ");
        TextColonia.setText(" ");
        TextFNacimiento.setText(" ");
        TextNControl.setText(" ");
        TextName.setText(" ");
        TextNumero.setText(" ");
        CBXEstado.setSelectedIndex(-1);
        CBXSexo.setSelectedIndex(-1);
        CheckAmbos.setSelected(false);
        CheckEspañol.setSelected(false);
        CheckEstudia.setSelected(false);
        CheckFrances.setSelected(false);
        CheckIngles.setSelected(false);
        CheckTrabaja.setSelected(false);
        TurnoVespertino.setSelected(false);
        TurnoMatutino.setSelected(false);
        RB_Electricidad.setSelected(false);
        RB_MecInd.setSelected(false);
        RB_Mecatronica.setSelected(false);
        RB_Ofimatica.setSelected(false);
        RB_Programacion.setSelected(false);
        RB_RH.setSelected(false);
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
       
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void CheckInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInglesActionPerformed
        if(CheckIngles.isSelected())
        {
            CheckEspañol.setEnabled(false);
            CheckFrances.setEnabled(false);
        }
        else
        {
            CheckEspañol.setEnabled(true);
            CheckFrances.setEnabled(true);
        }
        
 
    }//GEN-LAST:event_CheckInglesActionPerformed

    private void CheckAmbosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAmbosActionPerformed
        
        if(CheckAmbos.isSelected()){
        CheckEstudia.setEnabled(false);
        CheckTrabaja.setEnabled(false);
        }
        else{
        CheckEstudia.setEnabled(true);
        CheckTrabaja.setEnabled(true);
        }
    }//GEN-LAST:event_CheckAmbosActionPerformed

    private void CheckTrabajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckTrabajaActionPerformed
       
        if(CheckTrabaja.isSelected()){
        CheckEstudia.setEnabled(false);
        CheckAmbos.setEnabled(false);
        }
        else{
        CheckEstudia.setEnabled(true);
        CheckAmbos.setEnabled(true);
        }
    }//GEN-LAST:event_CheckTrabajaActionPerformed

    private void CheckEstudiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckEstudiaActionPerformed
     
        if(CheckEstudia.isSelected()){
        CheckTrabaja.setEnabled(false);
        CheckAmbos.setEnabled(false);
        }
        else{
        CheckTrabaja.setEnabled(true);
        CheckAmbos.setEnabled(true);
        }
    }//GEN-LAST:event_CheckEstudiaActionPerformed

    private void RB_OfimaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_OfimaticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_OfimaticaActionPerformed

    private void RB_ProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_ProgramacionActionPerformed
   

// TODO add your handling code here:
    }//GEN-LAST:event_RB_ProgramacionActionPerformed

    private void CheckFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckFrancesActionPerformed
       if(CheckFrances.isSelected()){
        CheckIngles.setEnabled(false);
        CheckEspañol.setEnabled(false);
        }
        else{
        CheckIngles.setEnabled(true);
        CheckEspañol.setEnabled(true);
        }
    }//GEN-LAST:event_CheckFrancesActionPerformed

    private void CheckEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckEspañolActionPerformed
        if(CheckEspañol.isSelected()){
        CheckIngles.setEnabled(false);
        CheckFrances.setEnabled(false);
        }
        else{
        CheckIngles.setEnabled(true);
        CheckFrances.setEnabled(true);
        }
    }//GEN-LAST:event_CheckEspañolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Button;
    private javax.swing.JComboBox<String> CBXEstado;
    private javax.swing.JComboBox<String> CBXSexo;
    public javax.swing.JCheckBox CheckAmbos;
    public javax.swing.JCheckBox CheckEspañol;
    public javax.swing.JCheckBox CheckEstudia;
    public javax.swing.JCheckBox CheckFrances;
    public javax.swing.JCheckBox CheckIngles;
    public javax.swing.JCheckBox CheckTrabaja;
    public javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuCarrera;
    private javax.swing.JMenu MenuTurno;
    public javax.swing.JMenu OpcionesMenu;
    public javax.swing.JRadioButtonMenuItem RB_Electricidad;
    public javax.swing.JRadioButtonMenuItem RB_MecInd;
    public javax.swing.JRadioButtonMenuItem RB_Mecatronica;
    public javax.swing.JRadioButtonMenuItem RB_Ofimatica;
    public javax.swing.JRadioButtonMenuItem RB_Programacion;
    public javax.swing.JRadioButtonMenuItem RB_RH;
    public javax.swing.JTextField TextAMat;
    public javax.swing.JTextField TextAPatern;
    public javax.swing.JTextField TextCalle;
    public javax.swing.JTextField TextColonia;
    public javax.swing.JTextField TextFNacimiento;
    public javax.swing.JTextField TextNControl;
    public javax.swing.JTextField TextName;
    public javax.swing.JTextField TextNumero;
    public javax.swing.JRadioButtonMenuItem TurnoMatutino;
    public javax.swing.JRadioButtonMenuItem TurnoVespertino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
